### ISSUE TITLE
missing from nuget

### ISSUE THREAD

**Issue by f2calv** [Azure/azure-functions-availability-monitoring-extension#25]
@macrogreg one of my team was using the alpha version of 1.0.0-alpha.3 on NuGet but it's been removed (Microsoft.Azure.WebJobs.Extensions.AvailabilityMonitoring)

Can you confirm the git commit of the 1.0.0-alpha.3 so I can replicate the dll and add the package into our private feed?

**Comment by zakimaksyutov** [comment]
@f2calv, this solution is not supported.

**Comment by f2calv** [comment]
Totally understood, nonetheless the library is in use in a customer project (over which I have no control).
I wasn't asking for support, just the commit hash so I can make the best of a bad situation.
